version: '3'

services:
  db:
    image: mysql:8.0.21
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: trafficrules
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  backend:
    container_name: traffic-rules-backend
    build:
      context: $TRAFFIC_RULES_ROOT/backend/trafficrules/
      dockerfile: $TRAFFIC_RULES_ROOT/backend/trafficrules/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/trafficrules
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    container_name: traffic-rules-frontend
    build:
      context: $TRAFFIC_RULES_ROOT/frontend/
      dockerfile: $TRAFFIC_RULES_ROOT/frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
