ALTER TABLE `users`
	ADD COLUMN `registered` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() AFTER `name`,
	ADD COLUMN `last_activity` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() AFTER `registered`;