spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:trafficrules}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true